name: gamification_engine_tests
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Spring Boot Run
        run: |
          cd gamification-impl
          mvn clean compile spring-boot:start

      - name: Maven Clean Test
        run: |
          cd gamification-specs
          mvn clean test
