name: mvn tests
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  test:
    name: mvn tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Package
        run: |
          cd gamification-impl
          mvn clean package

      - name: Maven Spring Boot Run
        run: |
          cd gamification-impl
          mvn spring-boot:run &

      - name: Wait on Spring Boot
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:3000/'
          responseCode: 200
          timeout: 30000
          interval: 1000

      - name: Maven Clean Test
        run: |
          cd gamification-specs
          mvn clean test

