name: mvn tests
on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches: [ dev ]

jobs:
  mvn_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven build Spring Boot server
        run: |
          cd gamification-impl
          mvn clean package

      - name: Start Spring Boot server
        run: |
          cd gamification-impl
          mvn spring-boot:run

      - name: Wait for Spring Boot Server response
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:3000/'
          responseCode: 200
          timeout: 30000
          interval: 1000

      - name: Maven spring Boot tests
        run: |
          cd gamification-specs
          mvn clean test
